// This file is automatically generated. Do not edit it directly.
//
// EXCEÇÃO DOCUMENTADA (Bloco C do .lovable/plan.md — fase-ponte "zero NestJS"):
// Este arquivo foi editado manualmente para migrar o storage de sessão de
// `localStorage` para cookies via `@supabase/ssr`. Isso é pré-requisito da
// hidratação server-side (SSR) usada em `src/integrations/supabase/server-session.ts`
// e do bloqueio server-side em `src/routes/_authenticated.tsx`.
// Se este arquivo for regenerado pelo Lovable Cloud, esta edição precisa ser
// reaplicada. Ver MIGRATION_NOTES.md.
import { createBrowserClient } from '@supabase/ssr';
import type { Database } from './types';

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // createBrowserClient persiste a sessão em cookies (document.cookie),
  // permitindo que o servidor leia a sessão no SSR inicial via server-session.ts.
  return createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
